// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABn3phjmjZ1Y7jNOdokCekOX6rrXZEhvo',
    appId: '1:844185919243:web:9abe7d2848005313f10c0e',
    messagingSenderId: '844185919243',
    projectId: 'flutter-demo-e0e77',
    authDomain: 'flutter-demo-e0e77.firebaseapp.com',
    storageBucket: 'flutter-demo-e0e77.firebasestorage.app',
    measurementId: 'G-6QBH9N7R55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvWz8ZWkmhvcFBmMqym1hefb97NFWAC8M',
    appId: '1:844185919243:android:8a41dc9a8f0c75c2f10c0e',
    messagingSenderId: '844185919243',
    projectId: 'flutter-demo-e0e77',
    storageBucket: 'flutter-demo-e0e77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU-t5yhZiqy0Y-pDUgPQv9KPzZihu3Ovc',
    appId: '1:844185919243:ios:d36d7faf11426f51f10c0e',
    messagingSenderId: '844185919243',
    projectId: 'flutter-demo-e0e77',
    storageBucket: 'flutter-demo-e0e77.firebasestorage.app',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU-t5yhZiqy0Y-pDUgPQv9KPzZihu3Ovc',
    appId: '1:844185919243:ios:d36d7faf11426f51f10c0e',
    messagingSenderId: '844185919243',
    projectId: 'flutter-demo-e0e77',
    storageBucket: 'flutter-demo-e0e77.firebasestorage.app',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABn3phjmjZ1Y7jNOdokCekOX6rrXZEhvo',
    appId: '1:844185919243:web:6f03ef546b322500f10c0e',
    messagingSenderId: '844185919243',
    projectId: 'flutter-demo-e0e77',
    authDomain: 'flutter-demo-e0e77.firebaseapp.com',
    storageBucket: 'flutter-demo-e0e77.firebasestorage.app',
    measurementId: 'G-3VEBQ3K69P',
  );

}